### ISSUE TITLE
Reinstate the core plugin page

### ISSUE THREAD

**Issue by scottsweb** [Automattic/vip-go-mu-plugins#206]
**Things to check:**
- [x] ~~Should we add in the FPP adverts via admin notices?~~
- [x] Do we (yet) have sufficient hooks to add information about plugins loaded via wpcom_vip_load_plugins, or should we try and get these added via core in 4.6?

**Tasks**
- [x] Remove `remove_menu_page` call to re-instate plugins ui
- [x] Unbundle our feature partners UI / code
- [x] Introduce a new featured partners section
- [x] Test that bad plugins fail correctly https://github.com/Automattic/vip-dashboard/issues/48
- [ ] ~~Make sure the installation of plugins is disabled (related #112)~~
- [x] Make sure plugins activated by code cannot be bulk activated
- [x] https://github.com/Automattic/vip-dashboard/pull/56/files#diff-89ad60d19282ec7bc4917b8a060268ccR513

To be followed by #67 - remove all shared plugins

**Comment by scottsweb** [comment]
Plugin installation is disabled but there are certain elements in the UI that we need to tweak as per #112.
