### ISSUE TITLE
Compatibility with PHP 8.1

### ISSUE THREAD

**Issue by sjinks** [Automattic/vip-go-mu-plugins#2667]
This is an umbrella issue for all PHP 8.1-related bugs.

The goal is to make `vip-go-mu-plugins` fully compatible with PHP 8.1.

We use the following commands to run the test suite against PHP 8.1:

```bash
./bin/test.sh --php 8.1  --phpunit 9 --wp nightly
./bin/test.sh --php 8.1  --phpunit 9 --wp nightly --multisite 1
```

So far, the test suite generates 448 errors.

- [x] `PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /home/circleci/project/000-debug/debug-mode.php on line 29` (#2668)
- [x] `PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/circleci/project/vip-helpers/class-user-cleanup.php on line 16` (#2668)
- [x] `PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /home/circleci/project/search/includes/classes/class-search.php on line 1902` (#2668)
- [x] `PHP Deprecated:  substr(): Passing null to parameter #1 ($string) of type string is deprecated in /home/circleci/project/vip-helpers/vip-utils.php on line 356` (#2668)
- [x] `PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/circleci/project/search/includes/classes/class-search.php on line 1537` (#2668)
- [x] `PHP Deprecated:  Implicit conversion from float 1652683804.007 to int loses precision in /home/circleci/project/tests/config/test-site-details-index.php on line 115` (#3155)

**Third-party plugins/dependencies:**
- [x] `Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/circleci/project/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 40`
- [x] `PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /home/circleci/project/search/elasticpress/includes/classes/Feature/Search/Synonyms.php on line 329`
- [ ] `Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/circleci/project/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 51`
- [ ] `Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/circleci/project/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 68`
- [ ] `Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/circleci/project/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 82`
- [ ] `Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/circleci/project/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 91`
- [ ] `Deprecated: Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/circleci/project/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 63`
- [ ] `Deprecated: Return type of Requests_Cookie_Jar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/circleci/project/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 73`
- [ ] `Deprecated: Return type of Requests_Cookie_Jar::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/circleci/project/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 89`
- [ ] `Deprecated: Return type of Requests_Cookie_Jar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/circleci/project/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 102`
- [ ] `Deprecated:  Return type of Requests_Cookie_Jar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/circleci/project/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 111`
- [x] `PHP Deprecated:  http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /home/circleci/project/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 345`

**Comment by sjinks** [comment]
With this "patch":

```diff
diff --git a/000-vip-init.php b/000-vip-init.php
index 2c132dbc9..0e9f1c8ff 100644
--- a/000-vip-init.php
+++ b/000-vip-init.php
@@ -272,3 +272,4 @@ if ( ! defined( 'WP_RUN_CORE_TESTS' ) || ! WP_RUN_CORE_TESTS ) {
 }
 
 do_action( 'vip_loaded' );
+error_reporting( error_reporting() & ~ ( E_DEPRECATED | E_USER_DEPRECATED ) );
```

all tests pass.
